var ORIProblemCreator = Class.create();

ORIProblemCreator.prototype = {
  initialize: function() {},

  createProblem: function(recommendationSysId) {
    var recGr = new GlideRecord('x_ori_ai_recommendation');
    if (!recGr.get(recommendationSysId)) {
      gs.error('ORIProblemCreator.createProblem: recommendation not found: ' + recommendationSysId);
      return false;
    }

    var existingProblemId = this._findExistingProblem(recGr);
    if (existingProblemId) {
      recGr.setValue('problem', existingProblemId);
      recGr.setValue('state', 'linked_to_existing');
      recGr.update();
      this._associateIncidents(recGr, existingProblemId);
      return existingProblemId;
    }

    var problemGr = new GlideRecord('problem');
    problemGr.initialize();
    problemGr.setValue('short_description', recGr.getValue('problem_statement'));
    problemGr.setValue('description',
      'Pattern: ' + (recGr.getValue('pattern_name') || '') + '\n\n' +
      'Root Cause Hypothesis:\n' + (recGr.getValue('root_cause_hypothesis') || '') +
      '\n\nRecommendation:\n' + (recGr.getValue('recommendation_text') || '') +
      '\n\nGenerated by Operational Risk Intelligence — Run: ' + recGr.getDisplayValue('analysis_run'));

    // Resolve primary_ci display name to sys_id
    var primaryCi = recGr.getValue('primary_ci') || '';
    if (primaryCi) {
      var ciGr = new GlideRecord('cmdb_ci');
      ciGr.addQuery('name', primaryCi);
      ciGr.query();
      if (ciGr.next()) {
        problemGr.setValue('cmdb_ci', ciGr.getUniqueValue());
      }
    }

    var problemSysId = problemGr.insert();

    this._associateIncidents(recGr, problemSysId);

    recGr.setValue('problem', problemSysId);
    recGr.setValue('approved_by', gs.getUserID());
    recGr.setValue('approval_date', new GlideDateTime().getDisplayValue());
    recGr.update();

    return problemSysId;
  },

  // Duplicate guard: open Problem where CI matches primary_ci
  // AND short_description starts with first 40 chars of pattern_name
  _findExistingProblem: function(recGr) {
    var patternName = recGr.getValue('pattern_name') || '';
    var primaryCi = recGr.getValue('primary_ci') || '';

    if (!patternName || !primaryCi) { return null; }

    // Look up CI sys_id from display name
    var ciGr = new GlideRecord('cmdb_ci');
    ciGr.addQuery('name', primaryCi);
    ciGr.query();
    if (!ciGr.next()) { return null; }
    var ciSysId = ciGr.getUniqueValue();

    var prefix = patternName.length > 40 ? patternName.substring(0, 40) : patternName;

    var problemGr = new GlideRecord('problem');
    problemGr.addQuery('cmdb_ci', ciSysId);
    problemGr.addQuery('short_description', 'STARTSWITH', prefix);
    problemGr.addQuery('state', 'NOT IN', '4,5');
    problemGr.query();

    if (problemGr.next()) { return problemGr.getUniqueValue(); }
    return null;
  },

  // Parse linked_incidents JSON from recommendation and set problem_id on each incident
  _associateIncidents: function(recGr, problemSysId) {
    var linkedJson = recGr.getValue('linked_incidents') || '[]';
    var linked;
    try {
      linked = JSON.parse(linkedJson);
    } catch (e) {
      gs.warn('ORIProblemCreator._associateIncidents: could not parse linked_incidents — ' + e.message);
      return;
    }

    for (var i = 0; i < linked.length; i++) {
      var incSysId = linked[i].sys_id;
      if (!incSysId) { continue; }
      var incGr = new GlideRecord('incident');
      if (incGr.get(incSysId)) {
        incGr.setValue('problem_id', problemSysId);
        incGr.update();
      }
    }
  },

  type: 'ORIProblemCreator'
};
