var ORIProblemCreator = Class.create();

ORIProblemCreator.prototype = {
  initialize: function() {},

  createProblem: function(recommendationSysId) {
    var recGr = new GlideRecord('x_ori_ai_recommendation');
    if (!recGr.get(recommendationSysId)) {
      gs.error('ORIProblemCreator.createProblem: recommendation not found: ' + recommendationSysId);
      return false;
    }

    var existingProblemId = this._findExistingProblem(recGr);
    if (existingProblemId) {
      recGr.setValue('problem', existingProblemId);
      recGr.setValue('state', 'linked_to_existing');
      recGr.update();
      this._associateIncidents(recommendationSysId, existingProblemId);
      return existingProblemId;
    }

    var problemGr = new GlideRecord('problem');
    problemGr.initialize();
    problemGr.setValue('short_description', recGr.getValue('problem_statement'));

    var rootCauseHypothesis = recGr.getValue('root_cause_hypothesis') || '';
    var recommendationText = recGr.getValue('recommendation_text') || '';
    var analysisRunDisplay = recGr.getDisplayValue('analysis_run');
    var description = 'Root Cause Hypothesis:\n' + rootCauseHypothesis +
      '\n\nRecommendation:\n' + recommendationText +
      '\n\nGenerated by Operational Risk Intelligence — Run: ' + analysisRunDisplay;
    problemGr.setValue('description', description);

    var clusterSysId = recGr.getValue('cluster');
    if (clusterSysId) {
      var clusterGr = new GlideRecord('x_ori_incident_cluster');
      if (clusterGr.get(clusterSysId)) {
        var assignmentGroup = clusterGr.getValue('assignment_group');
        var cmdbCi = clusterGr.getValue('ci');
        var category = clusterGr.getValue('category');
        if (assignmentGroup) {
          problemGr.setValue('assignment_group', assignmentGroup);
        }
        if (cmdbCi) {
          problemGr.setValue('cmdb_ci', cmdbCi);
        }
        if (category) {
          problemGr.setValue('category', category);
        }
      }
    }

    var problemSysId = problemGr.insert();

    this._associateIncidents(recommendationSysId, problemSysId);

    recGr.setValue('problem', problemSysId);
    recGr.setValue('approved_by', gs.getUserID());
    recGr.setValue('approval_date', new GlideDateTime().getDisplayValue());
    recGr.update();

    return problemSysId;
  },

  _findExistingProblem: function(recGr) {
    var clusterSysId = recGr.getValue('cluster');
    if (!clusterSysId) {
      return null;
    }

    var clusterGr = new GlideRecord('x_ori_incident_cluster');
    if (!clusterGr.get(clusterSysId)) {
      return null;
    }

    var ci = clusterGr.getValue('ci');
    var category = clusterGr.getValue('category');

    if (!ci || ci === '') {
      return null;
    }

    var problemGr = new GlideRecord('problem');
    problemGr.addQuery('cmdb_ci', ci);
    if (category) {
      problemGr.addQuery('category', category);
    }
    problemGr.addQuery('state', 'NOT IN', '4,5');
    problemGr.query();

    if (problemGr.next()) {
      return problemGr.getValue('sys_id');
    }

    return null;
  },

  _associateIncidents: function(recommendationSysId, problemSysId) {
    var riGr = new GlideRecord('x_ori_recommendation_incident');
    riGr.addQuery('recommendation', recommendationSysId);
    riGr.query();

    while (riGr.next()) {
      var incidentSysId = riGr.getValue('incident');
      if (!incidentSysId) {
        continue;
      }
      var incidentGr = new GlideRecord('incident');
      if (incidentGr.get(incidentSysId)) {
        incidentGr.setValue('problem_id', problemSysId);
        incidentGr.update();
      }
    }
  },

  type: 'ORIProblemCreator'
};
